# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Metropolis-Hastings MCMC with Adaptive Proposal Kernel
#'
#' @param target the a R function that must return the log likelihood of the target distribution we want to sample from
#' @param init_theta a vector of initial parameter values
#' @param covmat the covariance matrix of the proposal distribution
#' @param n_iterations the integer value, how long to run the chain
#' @param adapt_size_start the number of accepted jumps after which to begin adapting size of proposal covariance matrix
#' @param info the print information on chain every X n_iterations
#' @param seedMH the seed of RNG
#' @param eps the a constant that we may choose very small compared to the size of S
#' @return R list: theta_trace,sigma_empirical,acceptance_rate
#' @examples
#' library(mcmcSampler)
#' p.log <- function(x) {
#' B <- 0.03 # controls 'bananacity'
#' -x[1]^2/200 - 1/2*(x[2]+B*x[1]^2-100*B)^2
#' }
#' set.seed(123)
#'  banana1 <- adaptMCMC(target=p.log,init_theta=c(10,10),covmat=diag(c(1,1)),n_iterations=1e3,adapt_size_start=10,acceptance_rate_weight=0,acceptance_window=0,info=1e2, seedMH = 123)
#'
#' par(mfrow=c(1,2))
#' x1 <- seq(-15, 15, length=100)
#' x2 <- seq(-15, 15, length=100)
#' d.banana <- matrix(apply(expand.grid(x1, x2), 1, p.log), nrow=100)
#' image(x1, x2, exp(d.banana), col=cm.colors(60))
#' contour(x1, x2, exp(d.banana), add=TRUE, col=gray(0.6))
#' lines(banana1$theta_trace, type='l')
#' matplot(banana1$theta_trace,type="l")
adaptMCMC <- function(target, init_theta, covmat, n_iterations, adapt_size_start, acceptance_rate_weight, acceptance_window, info, seedMH = 1, eps = 0.05) {
    .Call(`_mcmcSampler_adaptMCMC`, target, init_theta, covmat, n_iterations, adapt_size_start, acceptance_rate_weight, acceptance_window, info, seedMH, eps)
}

#' Random Walk Metropolis-Hastings MCMC
#'
#' @param target the R function that must return the log likelihood of the target distribution we want to sample from
#' @param init_theta the vector of initial parameter values
#' @param covmat the covariance matrix of the proposal distribution
#' @param n_iterations the integer value, how long to run the chain
#' @return R list: theta_trace, acceptance_rate
#' @examples
#' library(mcmcSampler)
#' p.log <- function(x) {
#'   B <- 0.03 # controls 'bananacity'
#'   -x[1]^2/200 - 1/2*(x[2]+B*x[1]^2-100*B)^2
#' }
#' sample <- rwMCMC(target=p.log, init_theta=c(10,10), covmat=diag(c(1,1)),n_iterations=1e4)
rwMCMC <- function(target, init_theta, covmat, n_iterations) {
    .Call(`_mcmcSampler_rwMCMC`, target, init_theta, covmat, n_iterations)
}

sub1 <- function(x, i) {
    .Call(`_mcmcSampler_sub1`, x, i)
}

sub2 <- function(x, a, b) {
    .Call(`_mcmcSampler_sub2`, x, a, b)
}

negSubCol <- function(x, i) {
    .Call(`_mcmcSampler_negSubCol`, x, i)
}

negSubRow <- function(x, i) {
    .Call(`_mcmcSampler_negSubRow`, x, i)
}

#' Get a sample of size n from the specificed truncated Gaussian distribution.
#'
#' @param n integer number of samples to take
#' @param mu mean of distribution
#' @param sigma standard deviation of distribution
#' @param a lower truncation bound
#' @param b upper truncation bound
#' @return a sample of size n from the specificed truncated Gaussian distribution
#' @examples
#' library(mcmcSampler)
#' set.seed(100)
#' rtnorm_gibbs(n=100,mu=0, sigma=1, a=2, b=4)
rtnorm_gibbs <- function(n, mu, sigma, a, b) {
    .Call(`_mcmcSampler_rtnorm_gibbs`, n, mu, sigma, a, b)
}

#' Get a sample of size n from the specified truncated multivariate Gaussian distribution
#'
#' @param n integer number of samples to take
#' @param mu mean of distribution
#' @param sigma standard deviation of distribution
#' @param lower lower truncation bound
#' @param upper upper truncation bound
#' @param init_state initial starting state of the MCMC chain
#' @return a sample of size n from the specified truncated multivariate Gaussian distribution
#' @examples
#' library(mcmcSampler)
#' set.seed(100)
#' mean <- c(-1, 1)
#' sigma <- matrix(data = c(1.0, -0.5, -0.5, 1.0), ncol = 2, nrow = 2)
#' rtmvnorm_gibbs(1e4, mean, sigma, c(-Inf,0), c(10,10), c(2,2) )
rtmvnorm_gibbs <- function(n, mu, sigma, lower, upper, init_state) {
    .Call(`_mcmcSampler_rtmvnorm_gibbs`, n, mu, sigma, lower, upper, init_state)
}

